---
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  # The name of the Recording is the same as the resulting `SeccompProfile` CRD
  # after reconciliation.
  name: goof-recording
  namespace: security-profiles-operator
spec:
  kind: SeccompProfile
  podSelector:
    matchLabels:
      app: goof
