apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SeccompProfile
metadata:
  generation: 1
  labels:
    app: goof
  name: goof
  namespace: security-profiles-operator
spec:
  architectures:
  - SCMP_ARCH_X86_64
  - SCMP_ARCH_X86
  - SCMP_ARCH_X32
  defaultAction: SCMP_ACT_ERRNO
  syscalls:
  - action: SCMP_ACT_ALLOW
    names:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - chown
    - clock_getres
    - clone
    - close
    - dup2
    - epoll_create
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - epoll_wait
    - eventfd2
    - execve
    - exit
    - exit_group
    - faccessat
    - fadvise64
    - fgetxattr
    - fsetxattr
    - fchdir
    - fchown
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents
    - getdents64
    - getegid
    - geteuid
    - getgid
    - getpid
    - getppid
    - getrlimit
    - getsockname
    - getuid
    - ioctl
    - io_setup
    - kill
    - listen
    - lseek
    - lstat
    - madvise
    - mkdir
    - mmap
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - open
    - openat
    - pipe2
    - poll
    - prctl
    - pread64
    - prlimit64
    - pwrite64
    - read
    - readlink
    - recvfrom
    - recvmsg
    - rename
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - rt_sigsuspend
    - sched_getaffinity
    - seccomp
    - select
    - sendto
    - sendfile
    - sendmsg
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setitimer
    - setresgid
    - setresuid
    - setsockopt
    - setuid
    - socket
    - socketpair
    - stat
    - statfs
    - sysinfo
    - tgkill
    - times
    - umask
    - unlink
    - utimensat
    - uname
    - wait4
    - write
    - writev
